<a href="https://colab.research.google.com/github/miriam-silva/PLN/blob/main/AtividadePratica_Miriam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Projeto Integrado de PLN

In [122]:
!pip install -q spacy nltk
!python -m spacy download pt_core_news_sm
!python -m spacy download pt_core_news_md

Collecting pt-core-news-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/pt_core_news_sm-3.8.0/pt_core_news_sm-3.8.0-py3-none-any.whl (13.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 64.9 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('pt_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
Collecting pt-core-news-md==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/pt_core_news_md-3.8.0/pt_core_news_md-3.8.0-py3-none-any.whl (42.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 MB 13.3 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('pt_core_news_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [123]:
import spacy
import nltk
import pandas as pd
import numpy as np

from nltk.corpus import stopwords
from nltk.stem import RSLPStemmer

nltk.download('stopwords')
nltk.download('rslp')

nlp = spacy.load("pt_core_news_sm")
nlp_md = spacy.load("pt_core_news_md")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package rslp to /root/nltk_data...
[nltk_data]   Package rslp is already up-to-date!

In [124]:
corpus = [
    "Bom dia! Meu nome é Marcos Ferreira e tenho interesse no apartamento anunciado na Rua Voluntários da Pátria, em Matão.",
    "Vocês trabalham com financiamento pela Caixa Econômica Federal para imóveis usados?",
    "Gostaria de agendar uma visita ao imóvel do bairro Jardim Europa nesta semana.",
    "Qual é o valor do condomínio e do IPTU do apartamento no centro de Araraquara?",
    "A casa na Vila Mariana ainda está disponível para locação?",
    "Aceitam fiador ou seguro fiança para o contrato de aluguel?",
    "Sou a corretora Camila Souza, entrando em contato sobre o interesse do cliente João Pedro no imóvel de Ribeirão Preto.",
    "O apartamento é novo ou já foi reformado recentemente?",
    "Qual o prazo médio de aprovação do financiamento bancário?",
    "Estou buscando um imóvel próximo ao Shopping Iguatemi, para compra à vista.",
    "O sobrado no bairro Santa Cecília aceita animais de estimação?",
    "Poderiam enviar mais fotos do apartamento e da planta baixa?",
    "Qual é a taxa de juros aplicada pelo Banco do Brasil nesse tipo de financiamento?",
    "A casa alugada tem vaga de garagem coberta?",
    "Tenho interesse em investir em um imóvel para locação de longo prazo.",
    "Poderia me indicar imóveis disponíveis na região central de Matão?"
]

In [125]:
# Processando todos os documentos do corpus
docs = [nlp(texto) for texto in corpus]

## 1. Tokenização

In [126]:
# Etapa 1 — Tokenização

for i in [0, 1]:
    print(f"Documento {i+1}:")
    print([token.text for token in docs[i]])
    print()

Documento 1:
['Bom', 'dia', '!', 'Meu', 'nome', 'é', 'Marcos', 'Ferreira', 'e', 'tenho', 'interesse', 'no', 'apartamento', 'anunciado', 'na', 'Rua', 'Voluntários', 'da', 'Pátria', ',', 'em', 'Matão', '.']

Documento 2:
['Vocês', 'trabalham', 'com', 'financiamento', 'pela', 'Caixa', 'Econômica', 'Federal', 'para', 'imóveis', 'usados', '?']

## 2. Stopwords, Stemming e Lematização

In [127]:
# ETAPA 2 - STOPWORDS, STEMMING E LEMATIZAÇÃO

# Escolhendo o Documento 1 do corpus
frase = corpus[0]
doc = nlp(frase)

# Stopwords em português
stop_pt = set(stopwords.words("portuguese"))

# Tokens sem pontuação e sem stopwords
tokens_filtrados = [
    token
    for token in doc
    if not token.is_punct
    and not token.is_space
    and token.text.lower() not in stop_pt
]

# Textos após remoção de stopwords
tokens_sem_stopwords = [
    token.text for token in tokens_filtrados
]

# Stemming aplicado somente aos tokens filtrados
stemmer = RSLPStemmer()

stems = [
    stemmer.stem(token.text.lower())
    for token in tokens_filtrados
]

# Lematização aplicada aos tokens filtrados
lemas = [
    token.lemma_.lower()
    for token in tokens_filtrados
]

print("Frase original:")
print(frase)

print("\nTokens sem pontuação e sem stopwords:")
print(tokens_sem_stopwords)

print("\nStemming:")
print(stems)

print("\nLematização:")
print(lemas)

Frase original:
Bom dia! Meu nome é Marcos Ferreira e tenho interesse no apartamento anunciado na Rua Voluntários da Pátria, em Matão.

Tokens sem pontuação e sem stopwords:
['Bom', 'dia', 'nome', 'Marcos', 'Ferreira', 'interesse', 'apartamento', 'anunciado', 'Rua', 'Voluntários', 'Pátria', 'Matão']

Stemming:
['bom', 'dia', 'nom', 'marc', 'ferr', 'inter', 'apart', 'anunci', 'rua', 'voluntári', 'pátr', 'mat']

Lematização:
['bom', 'dia', 'nome', 'marcos', 'ferreira', 'interesse', 'apartamento', 'anunciar', 'rua', 'voluntários', 'pátria', 'matão']

In [128]:
# Tabela comparativa

tabela_etapa2 = pd.DataFrame({
    "Token": tokens_sem_stopwords,
    "Stemming": stems,
    "Lematização": lemas
})

tabela_etapa2

          Token   Stemming  Lematização
0           Bom        bom          bom
1           dia        dia          dia
2          nome        nom         nome
3        Marcos       marc       marcos
4      Ferreira       ferr     ferreira
5     interesse      inter    interesse
6   apartamento      apart  apartamento
7     anunciado     anunci     anunciar
8           Rua        rua          rua
9   Voluntários  voluntári  voluntários
10       Pátria       pátr       pátria
11        Matão        mat        matão

## 3. Análise Sintática

In [129]:
# ETAPA 3 - ANÁLISE SINTÁTICA

frases_sintaticas = [
    corpus[1],
    corpus[3]
]

docs_sintaticos = [nlp(frase) for frase in frases_sintaticas]

for i, doc in enumerate(docs_sintaticos):
    print(f"\nFrase {i+1}:")
    print(doc.text)

    print("\nTokens, classe gramatical e dependência:")
    for token in doc:
        print(
            f"{token.text:20} "
            f"POS={token.pos_:10} "
            f"DEP={token.dep_:10} "
            f"HEAD={token.head.text}"
        )

Frase 1:
Vocês trabalham com financiamento pela Caixa Econômica Federal para imóveis usados?

Tokens, classe gramatical e dependência:
Vocês                POS=PRON       DEP=nsubj      HEAD=trabalham
trabalham            POS=VERB       DEP=ROOT       HEAD=trabalham
com                  POS=ADP        DEP=case       HEAD=financiamento
financiamento        POS=NOUN       DEP=obl        HEAD=trabalham
pela                 POS=ADP        DEP=case       HEAD=Caixa
Caixa                POS=PROPN      DEP=nmod       HEAD=financiamento
Econômica            POS=PROPN      DEP=flat:name  HEAD=Caixa
Federal              POS=PROPN      DEP=flat:name  HEAD=Caixa
para                 POS=ADP        DEP=case       HEAD=imóveis
imóveis              POS=NOUN       DEP=obl        HEAD=trabalham
usados               POS=VERB       DEP=acl        HEAD=imóveis
?                    POS=PUNCT      DEP=punct      HEAD=trabalham

Frase 2:
Qual é o valor do condomínio e do IPTU do apartamento no centro de Araraquara?

Tokens, classe gramatical e dependência:
Qual                 POS=PRON       DEP=ROOT       HEAD=Qual
é                    POS=AUX        DEP=cop        HEAD=Qual
o                    POS=DET        DEP=det        HEAD=valor
valor                POS=NOUN       DEP=nsubj      HEAD=Qual
do                   POS=ADP        DEP=case       HEAD=condomínio
condomínio           POS=NOUN       DEP=nmod       HEAD=valor
e                    POS=CCONJ      DEP=cc         HEAD=IPTU
do                   POS=ADP        DEP=case       HEAD=IPTU
IPTU                 POS=PROPN      DEP=conj       HEAD=condomínio
do                   POS=ADP        DEP=case       HEAD=apartamento
apartamento          POS=NOUN       DEP=nmod       HEAD=IPTU
no                   POS=ADP        DEP=case       HEAD=centro
centro               POS=NOUN       DEP=nmod       HEAD=apartamento
de                   POS=ADP        DEP=case       HEAD=Araraquara
Araraquara           POS=PROPN      DEP=nmod       HEAD=centro
?                    POS=PUNCT      DEP=punct      HEAD=Qual

In [130]:
# Identificação da ROOT e análise do caso especial

for i, doc in enumerate(docs_sintaticos):

    print("\n" + "=" * 60)
    print(f"Frase {i+1}: {doc.text}")

    root = [token for token in doc if token.dep_ == "ROOT"][0]

    print("\nROOT:")
    print(f"Palavra: {root.text}")
    print(f"POS: {root.pos_}")
    print(f"Dependência: {root.dep_}")

    if root.pos_ == "VERB":
        print("A ROOT é um verbo comum.")

    elif any(token.dep_ == "cop" for token in doc):
        copula = [
            token.text
            for token in doc
            if token.dep_ == "cop"
        ]

        print("A ROOT não é um verbo comum.")
        print(
            f"É um caso especial de construção copular. "
            f"O verbo de cópula identificado foi: {', '.join(copula)}."
        )

    else:
        print(
            "A ROOT não é um verbo comum e deve ser interpretada "
            "considerando a estrutura específica da frase."
        )

============================================================
Frase 1: Vocês trabalham com financiamento pela Caixa Econômica Federal para imóveis usados?

ROOT:
Palavra: trabalham
POS: VERB
Dependência: ROOT
A ROOT é um verbo comum.

============================================================
Frase 2: Qual é o valor do condomínio e do IPTU do apartamento no centro de Araraquara?

ROOT:
Palavra: Qual
POS: PRON
Dependência: ROOT
A ROOT não é um verbo comum.
É um caso especial de construção copular. O verbo de cópula identificado foi: é.

In [131]:
# Análise dos Sintagmas

for i, doc in enumerate(docs_sintaticos):

    print("\n" + "=" * 60)
    print(f"Frase {i+1}: {doc.text}")

    # Identificação do sujeito
    sujeitos = [
        token for token in doc
        if token.dep_ in ("nsubj", "nsubj:pass")
    ]

    # Identificação da ROOT
    root = [
        token for token in doc
        if token.dep_ == "ROOT"
    ][0]

    print("\nSintagma Nominal (SN):")

    if sujeitos:
        for sujeito in sujeitos:
            sn = [
                token.text
                for token in sujeito.subtree
                if not token.is_punct
            ]
            print(" ".join(sn))
    else:
        print("Não há sujeito nominal explícito identificado pelo modelo.")

    print("\nSintagma Verbal (SV):")

    if root.pos_ == "VERB":
        # Começa pelo verbo ROOT
        sv_tokens = [
            token.text
            for token in root.subtree
            if not token.is_punct
            and token not in sujeitos
        ]

        print(" ".join(sv_tokens))

    elif any(token.dep_ == "cop" for token in doc):
        copula = [
            token.text
            for token in doc
            if token.dep_ == "cop"
        ]

        print(
            f"Construção copular. O verbo de cópula identificado foi: "
            f"{', '.join(copula)}."
        )

    else:
        print(
            "Não foi identificado um Sintagma Verbal convencional "
            "a partir da estrutura fornecida pelo modelo."
        )

============================================================
Frase 1: Vocês trabalham com financiamento pela Caixa Econômica Federal para imóveis usados?

Sintagma Nominal (SN):
Vocês

Sintagma Verbal (SV):
trabalham com financiamento pela Caixa Econômica Federal para imóveis usados

============================================================
Frase 2: Qual é o valor do condomínio e do IPTU do apartamento no centro de Araraquara?

Sintagma Nominal (SN):
o valor do condomínio e do IPTU do apartamento no centro de Araraquara

Sintagma Verbal (SV):
Construção copular. O verbo de cópula identificado foi: é.

**Comentário sobre o resultado:**
A frase apresenta uma construção copular. O verbo **“é”** funciona como cópula e o spaCy identifica **“Qual”** como `ROOT`, em vez de tratá-lo como núcleo verbal. Isso ocorre devido à estrutura sintática da pergunta “Qual é o valor...”.

## 4. Interpretação Semântica

In [132]:
# ETAPA 4 - INTERPRETAÇÃO SEMÂNTICA

resultados_semanticos = []

for palavra1, palavra2 in pares:
    doc1 = nlp_md(palavra1)
    doc2 = nlp_md(palavra2)

    similaridade = doc1.similarity(doc2)

    resultados_semanticos.append({
        "Palavra 1": palavra1,
        "Palavra 2": palavra2,
        "Similaridade": round(similaridade, 4)
    })

tabela_semantica = pd.DataFrame(resultados_semanticos)

tabela_semantica

       Palavra 1 Palavra 2  Similaridade
0    apartamento    imóvel        0.6667
1  financiamento   aluguel        0.3090

**Comentário sobre o resultado:** A similaridade entre “apartamento” e “imóvel” foi 0,6667, indicando uma relação semântica maior entre os dois termos. Esse resultado faz sentido, pois ambos estão relacionados ao mesmo contexto imobiliário. Já “financiamento” e “aluguel” apresentaram similaridade de 0,3090. O valor é menor, mas ainda existe uma relação temática, pois os dois termos aparecem associados a situações de compra, locação ou utilização de imóveis.

## 5. Extração de Features

In [133]:
# ETAPA 5 - EXTRAÇÃO DE FEATURES

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [134]:
# Lematizando todos os documentos

corpus_lematizado = []

for doc in docs:

    lemas_doc = [
        token.lemma_.lower()
        for token in doc
        if not token.is_punct
        and not token.is_space
    ]

    corpus_lematizado.append(" ".join(lemas_doc))

print("Corpus lematizado:\n")

for i, texto in enumerate(corpus_lematizado):
    print(f"Documento {i+1}:")
    print(texto)
    print()

Corpus lematizado:

Documento 1:
bom dia meu nome ser marcos ferreira e ter interesse em o apartamento anunciar em o rua voluntários de o pátria em matão

Documento 2:
você trabalhar com financiamento por o caixa econômica federal para imóvel usar

Documento 3:
gostaria de agendar um visita a o imóvel de o bairro jardim europa em este semana

Documento 4:
qual ser o valor de o condomínio e de o iptu de o apartamento em o centro de araraquara

Documento 5:
o casa em o vila mariana ainda estar disponível para locação

Documento 6:
aceitam fiador ou seguro fiançar para o contrato de aluguel

Documento 7:
ser o corretora camila souza entrar em contato sobre o interesse de o cliente joão pedro em o imóvel de ribeirão preto

Documento 8:
o apartamento ser novo ou já ser reformar recentemente

Documento 9:
qual o prazo médio de aprovação de o financiamento bancário

Documento 10:
estar buscar um imóvel próximo a o shopping iguatemi para compra a o vista

Documento 11:
o sobrado em o bairro santa cecília aceitar animal de estimação

Documento 12:
poderiam enviar mais foto de o apartamento e de o planto baixo

Documento 13:
qual ser o taxa de juro aplicar por o banco de o brasil em esse tipo de financiamento

Documento 14:
o casa alugar ter vaga de garagem cobrir

Documento 15:
ter interesse em investir em um imóvel para locação de longo prazo

Documento 16:
poderia eu indicar imóvel disponível em o região central de matão

In [135]:
# Removendo stopwords do corpus lematizado

corpus_lematizado_sem_stopwords = []

for texto in corpus_lematizado:

    palavras = texto.split()

    palavras_filtradas = [
        palavra
        for palavra in palavras
        if palavra.lower() not in stop_pt
    ]

    corpus_lematizado_sem_stopwords.append(
        " ".join(palavras_filtradas)
    )

print("Corpus lematizado sem stopwords:\n")

for i, texto in enumerate(corpus_lematizado_sem_stopwords):
    print(f"Documento {i+1}:")
    print(texto)
    print()

Corpus lematizado sem stopwords:

Documento 1:
bom dia nome marcos ferreira ter interesse apartamento anunciar rua voluntários pátria matão

Documento 2:
trabalhar financiamento caixa econômica federal imóvel usar

Documento 3:
gostaria agendar visita imóvel bairro jardim europa semana

Documento 4:
valor condomínio iptu apartamento centro araraquara

Documento 5:
casa vila mariana ainda disponível locação

Documento 6:
aceitam fiador seguro fiançar contrato aluguel

Documento 7:
corretora camila souza entrar contato sobre interesse cliente joão pedro imóvel ribeirão preto

Documento 8:
apartamento novo reformar recentemente

Documento 9:
prazo médio aprovação financiamento bancário

Documento 10:
buscar imóvel próximo shopping iguatemi compra vista

Documento 11:
sobrado bairro santa cecília aceitar animal estimação

Documento 12:
poderiam enviar foto apartamento planto baixo

Documento 13:
taxa juro aplicar banco brasil tipo financiamento

Documento 14:
casa alugar ter vaga garagem cobrir

Documento 15:
ter interesse investir imóvel locação longo prazo

Documento 16:
poderia indicar imóvel disponível região central matão

In [136]:
# Bag-of-Words

bow_vectorizer = CountVectorizer()

bow_matrix = bow_vectorizer.fit_transform(
    corpus_lematizado_sem_stopwords
)

bow_df = pd.DataFrame(
    bow_matrix.toarray(),
    columns=bow_vectorizer.get_feature_names_out(),
    index=[
        f"Documento {i+1}"
        for i in range(len(corpus))
    ]
)

bow_df

,aceitam,aceitar,agendar,ainda,alugar,aluguel,animal,anunciar,apartamento,aplicar,...,ter,tipo,trabalhar,usar,vaga,valor,vila,visita,vista,voluntários
Documento 1,0,0,0,0,0,0,0,1,1,0,...,1,0,0,0,0,0,0,0,0,1
Documento 2,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0
Documento 3,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Documento 4,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
Documento 5,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
Documento 6,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Documento 7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Documento 8,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
Documento 9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Documento 10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
Documento 11,0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Documento 12,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
Documento 13,0,0,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
Documento 14,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
Documento 15,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Documento 16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [137]:
# Matriz TF-IDF

tfidf_vectorizer = TfidfVectorizer()

tfidf_matrix = tfidf_vectorizer.fit_transform(
    corpus_lematizado_sem_stopwords
)

tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=tfidf_vectorizer.get_feature_names_out(),
    index=[
        f"Documento {i+1}"
        for i in range(len(corpus))
    ]
)

tfidf_df

,aceitam,aceitar,agendar,ainda,alugar,aluguel,animal,anunciar,apartamento,aplicar,...,ter,tipo,trabalhar,usar,vaga,valor,vila,visita,vista,voluntários
Documento 1,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.295212,0.209067,0.000000,...,0.230046,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.295212
Documento 2,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.409325,0.409325,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Documento 3,0.000000,0.00000,0.374775,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.374775,0.000000,0.000000
Documento 4,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.301933,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.426342,0.000000,0.000000,0.000000,0.000000
Documento 5,0.000000,0.00000,0.000000,0.435389,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.435389,0.000000,0.000000,0.000000
Documento 6,0.408248,0.00000,0.000000,0.000000,0.000000,0.408248,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Documento 7,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Documento 8,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.378462,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Documento 9,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Documento 10,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.396487,0.000000
Documento 11,0.000000,0.38466,0.000000,0.000000,0.000000,0.000000,0.38466,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Documento 12,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.301933,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Documento 13,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.389036,...,0.000000,0.389036,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Documento 14,0.000000,0.00000,0.000000,0.000000,0.431706,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.336410,0.000000,0.000000,0.000000,0.431706,0.000000,0.000000,0.000000,0.000000,0.000000
Documento 15,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.345312,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Documento 16,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [138]:
# Quantidade de palavras únicas por documento

palavras_unicas = []

for i, texto in enumerate(corpus_lematizado_sem_stopwords):

    palavras = texto.split()
    unicas = set(palavras)

    palavras_unicas.append({
        "Documento": f"Documento {i+1}",
        "Palavras únicas": len(unicas)
    })

palavras_unicas_df = pd.DataFrame(palavras_unicas)

palavras_unicas_df

       Documento  Palavras únicas
0    Documento 1               13
1    Documento 2                7
2    Documento 3                8
3    Documento 4                6
4    Documento 5                6
5    Documento 6                6
6    Documento 7               13
7    Documento 8                4
8    Documento 9                5
9   Documento 10                7
10  Documento 11                7
11  Documento 12                6
12  Documento 13                7
13  Documento 14                6
14  Documento 15                7
15  Documento 16                7

In [139]:
maior_quantidade = palavras_unicas_df["Palavras únicas"].max()

documentos_maior = palavras_unicas_df[
    palavras_unicas_df["Palavras únicas"] == maior_quantidade
]

print(
    f"Os documentos com maior quantidade de palavras únicas "
    f"possuem {maior_quantidade} palavras únicas:"
)

print(documentos_maior)

Os documentos com maior quantidade de palavras únicas possuem 13 palavras únicas:
     Documento  Palavras únicas
0  Documento 1               13
6  Documento 7               13

**Comentário sobre o resultado:** Os Documentos 1 e 7 apresentam a maior quantidade de palavras únicas, com 13 palavras cada. Isso ocorre porque esses documentos apresentam diferentes nomes, locais e termos relacionados ao contexto imobiliário.

In [140]:
# Encontrando o maior valor de TF-IDF
maior_valor = tfidf_df.to_numpy().max()

print(f"Maior valor de TF-IDF: {maior_valor:.4f}")

print("\nOcorrências do maior valor:")

for linha, coluna in zip(
    *np.where(tfidf_df.to_numpy() == maior_valor)
):
    print(
        f"{tfidf_df.index[linha]} - "
        f"{tfidf_df.columns[coluna]}"
    )

Maior valor de TF-IDF: 0.5344

Ocorrências do maior valor:
Documento 8 - novo
Documento 8 - recentemente
Documento 8 - reformar

**Comentário sobre o resultado:** O maior valor de TF-IDF encontrado foi 0,5344, no Documento 8, para as palavras “novo”, “reformar” e “recentemente”. Essas palavras apresentam um peso elevado porque são termos característicos desse documento e possuem baixa frequência nos demais documentos do corpus. Isso faz com que sejam consideradas palavras importantes para representar o conteúdo específico do Documento 8.

## 6. Descoberta de Conhecimento em Textos (KDT)

In [141]:
# Documentos escolhidos para NER
documentos_ner = [
    corpus[0],
    corpus[6],
    corpus[12]
]

for i, texto in enumerate(documentos_ner):

    doc = nlp(texto)

    print("\n" + "=" * 70)
    print(f"Documento selecionado {i+1}")
    print(texto)

    print("\nEntidades encontradas:")

    if doc.ents:
        for ent in doc.ents:
            print(f"{ent.text} --> {ent.label_}")
    else:
        print("Nenhuma entidade encontrada.")

======================================================================
Documento selecionado 1
Bom dia! Meu nome é Marcos Ferreira e tenho interesse no apartamento anunciado na Rua Voluntários da Pátria, em Matão.

Entidades encontradas:
Marcos Ferreira --> PER
Rua Voluntários da Pátria --> LOC
Matão --> LOC

======================================================================
Documento selecionado 2
Sou a corretora Camila Souza, entrando em contato sobre o interesse do cliente João Pedro no imóvel de Ribeirão Preto.

Entidades encontradas:
Camila Souza --> PER
João Pedro --> PER
Ribeirão Preto --> LOC

======================================================================
Documento selecionado 3
Qual é a taxa de juros aplicada pelo Banco do Brasil nesse tipo de financiamento?

Entidades encontradas:
Banco do Brasil --> ORG

In [142]:
# Palavras-chave de cada documento

for i in range(len(tfidf_df)):

    documento = tfidf_df.iloc[i]

    principais = documento.sort_values(
        ascending=False
    ).head(5)

    print("\n" + "=" * 60)
    print(f"Documento {i+1}")

    for palavra, valor in principais.items():
        print(
            f"{palavra}: {valor:.4f}"
        )

============================================================
Documento 1
anunciar: 0.2952
bom: 0.2952
pátria: 0.2952
nome: 0.2952
marcos: 0.2952

============================================================
Documento 2
caixa: 0.4093
federal: 0.4093
econômica: 0.4093
trabalhar: 0.4093
usar: 0.4093

============================================================
Documento 3
agendar: 0.3748
gostaria: 0.3748
semana: 0.3748
visita: 0.3748
jardim: 0.3748

============================================================
Documento 4
araraquara: 0.4263
centro: 0.4263
condomínio: 0.4263
valor: 0.4263
iptu: 0.4263

============================================================
Documento 5
ainda: 0.4354
vila: 0.4354
mariana: 0.4354
disponível: 0.3792
locação: 0.3792

============================================================
Documento 6
aceitam: 0.4082
aluguel: 0.4082
contrato: 0.4082
fiançar: 0.4082
seguro: 0.4082

============================================================
Documento 7
contato: 0.2891
cliente: 0.2891
camila: 0.2891
souza: 0.2891
joão: 0.2891

============================================================
Documento 8
novo: 0.5344
reformar: 0.5344
recentemente: 0.5344
apartamento: 0.3785
ainda: 0.0000

============================================================
Documento 9
aprovação: 0.4786
bancário: 0.4786
médio: 0.4786
prazo: 0.4168
financiamento: 0.3730

============================================================
Documento 10
buscar: 0.3965
compra: 0.3965
iguatemi: 0.3965
próximo: 0.3965
shopping: 0.3965

============================================================
Documento 11
aceitar: 0.3847
animal: 0.3847
cecília: 0.3847
santa: 0.3847
sobrado: 0.3847

============================================================
Documento 12
baixo: 0.4263
foto: 0.4263
enviar: 0.4263
planto: 0.4263
poderiam: 0.4263

============================================================
Documento 13
aplicar: 0.3890
banco: 0.3890
brasil: 0.3890
taxa: 0.3890
tipo: 0.3890

============================================================
Documento 14
alugar: 0.4317
cobrir: 0.4317
garagem: 0.4317
vaga: 0.4317
casa: 0.3760

============================================================
Documento 15
longo: 0.4431
investir: 0.4431
locação: 0.3859
prazo: 0.3859
ter: 0.3453

============================================================
Documento 16
central: 0.4125
poderia: 0.4125
indicar: 0.4125
região: 0.4125
disponível: 0.3592

In [143]:
from sklearn.decomposition import LatentDirichletAllocation

In [144]:
# Treinamento do LDA

lda = LatentDirichletAllocation(
    n_components=2,
    random_state=42
)

lda_matrix = lda.fit_transform(bow_matrix)

print("LDA treinado com sucesso.")

LDA treinado com sucesso.

In [145]:
# Palavras principais de cada tópico

feature_names = bow_vectorizer.get_feature_names_out()

n_palavras = 8

for topico_idx, topico in enumerate(lda.components_):

    palavras = [
        feature_names[i]
        for i in topico.argsort()[
            :-n_palavras - 1:-1
        ]
    ]

    print(
        f"\nTópico {topico_idx + 1}:"
    )

    print(", ".join(palavras))

Tópico 1:
imóvel, financiamento, apartamento, preto, sobre, souza, ribeirão, joão

Tópico 2:
imóvel, ter, apartamento, interesse, locação, matão, casa, prazo

In [146]:
# Distribuição dos tópicos por documento

distribuicao_lda = pd.DataFrame(
    lda_matrix,
    columns=[
        "Tópico 1",
        "Tópico 2"
    ],
    index=[
        f"Documento {i+1}"
        for i in range(len(corpus))
    ]
)

distribuicao_lda

              Tópico 1  Tópico 2
Documento 1   0.039383  0.960617
Documento 2   0.075414  0.924586
Documento 3   0.936223  0.063777
Documento 4   0.920525  0.079475
Documento 5   0.081555  0.918445
Documento 6   0.925208  0.074792
Documento 7   0.959213  0.040787
Documento 8   0.884638  0.115362
Documento 9   0.902572  0.097428
Documento 10  0.067552  0.932448
Documento 11  0.067529  0.932471
Documento 12  0.077545  0.922455
Documento 13  0.933275  0.066725
Documento 14  0.901669  0.098331
Documento 15  0.073456  0.926544
Documento 16  0.920815  0.079185

**Comentário sobre o resultado:** O LDA identificou dois grupos de palavras no corpus. O Tópico 1 apresenta termos relacionados principalmente a financiamento, imóvel, apartamento e informações bancárias, enquanto o Tópico 2 reúne termos relacionados a locação, imóveis, interesse e localização. A distribuição por documento mostra que cada texto apresenta maior associação com um dos dois tópicos, embora alguns documentos também possuam uma pequena proporção do outro tópico.

In [147]:
# Tópico predominante em cada documento

distribuicao_lda["Tópico predominante"] = (
    distribuicao_lda[
        ["Tópico 1", "Tópico 2"]
    ].idxmax(axis=1)
)

distribuicao_lda

              Tópico 1  Tópico 2 Tópico predominante
Documento 1   0.039383  0.960617            Tópico 2
Documento 2   0.075414  0.924586            Tópico 2
Documento 3   0.936223  0.063777            Tópico 1
Documento 4   0.920525  0.079475            Tópico 1
Documento 5   0.081555  0.918445            Tópico 2
Documento 6   0.925208  0.074792            Tópico 1
Documento 7   0.959213  0.040787            Tópico 1
Documento 8   0.884638  0.115362            Tópico 1
Documento 9   0.902572  0.097428            Tópico 1
Documento 10  0.067552  0.932448            Tópico 2
Documento 11  0.067529  0.932471            Tópico 2
Documento 12  0.077545  0.922455            Tópico 2
Documento 13  0.933275  0.066725            Tópico 1
Documento 14  0.901669  0.098331            Tópico 1
Documento 15  0.073456  0.926544            Tópico 2
Documento 16  0.920815  0.079185            Tópico 1

## 7. Conclusão Integradora

As etapas do pipeline de PLN estão relacionadas e servem de base umas para as outras. A tokenização permitiu dividir os documentos em unidades que puderam ser analisadas individualmente. A normalização, por meio da remoção de stopwords, stemming e lematização, ajudou a reduzir variações das palavras e preparar o texto para a extração de características. A análise sintática acrescentou informações sobre a função das palavras e suas relações dentro das frases, enquanto a similaridade semântica permitiu comparar os significados de termos do corpus. Essas etapas foram importantes para as etapas finais, pois a lematização, por exemplo, foi utilizada antes da construção das matrizes Bag-of-Words e TF-IDF. Um exemplo concreto é a relação entre “apartamento” e “imóvel”: a análise semântica apresentou similaridade de 0,6667, enquanto o TF-IDF identificou as palavras “novo”, “reformar” e “recentemente” como alguns dos termos de maior peso no Documento 8. Dessa forma, as técnicas estudadas ao longo do semestre formam um pipeline integrado para transformar textos em informações que podem ser analisadas e utilizadas na descoberta de conhecimento.