<a href="https://colab.research.google.com/github/miriam-silva/PLN/blob/main/TesteDoisAtividadde.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Projeto Integrado de PLN

In [14]:
!pip install -q spacy nltk
!python -m spacy download pt_core_news_sm
!python -m spacy download pt_core_news_md

Collecting pt-core-news-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/pt_core_news_sm-3.8.0/pt_core_news_sm-3.8.0-py3-none-any.whl (13.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 57.8 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('pt_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
Collecting pt-core-news-md==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/pt_core_news_md-3.8.0/pt_core_news_md-3.8.0-py3-none-any.whl (42.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 MB 13.7 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('pt_core_news_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [15]:
import spacy
import nltk
import pandas as pd
import numpy as np

from nltk.corpus import stopwords
from nltk.stem import RSLPStemmer

nltk.download('stopwords')
nltk.download('rslp')

nlp = spacy.load("pt_core_news_sm")
nlp_md = spacy.load("pt_core_news_md")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package rslp to /root/nltk_data...
[nltk_data]   Package rslp is already up-to-date!

In [16]:
corpus = [
    "Bom dia! Meu nome é Marcos Ferreira e tenho interesse no apartamento anunciado na Rua Voluntários da Pátria, em Matão.",
    "Vocês trabalham com financiamento pela Caixa Econômica Federal para imóveis usados?",
    "Gostaria de agendar uma visita ao imóvel do bairro Jardim Europa nesta semana.",
    "Qual é o valor do condomínio e do IPTU do apartamento no centro de Araraquara?",
    "A casa na Vila Mariana ainda está disponível para locação?",
    "Aceitam fiador ou seguro fiança para o contrato de aluguel?",
    "Sou a corretora Camila Souza, entrando em contato sobre o interesse do cliente João Pedro no imóvel de Ribeirão Preto.",
    "O apartamento é novo ou já foi reformado recentemente?",
    "Qual o prazo médio de aprovação do financiamento bancário?",
    "Estou buscando um imóvel próximo ao Shopping Iguatemi, para compra à vista.",
    "O sobrado no bairro Santa Cecília aceita animais de estimação?",
    "Poderiam enviar mais fotos do apartamento e da planta baixa?",
    "Qual é a taxa de juros aplicada pelo Banco do Brasil nesse tipo de financiamento?",
    "A casa alugada tem vaga de garagem coberta?",
    "Tenho interesse em investir em um imóvel para locação de longo prazo.",
    "Poderia me indicar imóveis disponíveis na região central de Matão?"
]

In [17]:
# Processando todos os documentos do corpus
docs = [nlp(texto) for texto in corpus]

## 1. Tokenização

In [18]:
# Etapa 1 — Tokenização

for i in [0, 1]:
    print(f"Documento {i+1}:")
    print([token.text for token in docs[i]])
    print()

Documento 1:
['Bom', 'dia', '!', 'Meu', 'nome', 'é', 'Marcos', 'Ferreira', 'e', 'tenho', 'interesse', 'no', 'apartamento', 'anunciado', 'na', 'Rua', 'Voluntários', 'da', 'Pátria', ',', 'em', 'Matão', '.']

Documento 2:
['Vocês', 'trabalham', 'com', 'financiamento', 'pela', 'Caixa', 'Econômica', 'Federal', 'para', 'imóveis', 'usados', '?']

## 2. Stopwords, Stemming e Lematização

In [19]:
# ETAPA 2 - STOPWORDS, STEMMING E LEMATIZAÇÃO

# Escolhendo o Documento 1 do corpus
frase = corpus[0]

doc = nlp(frase)

# Stopwords em português
stop_pt = set(stopwords.words("portuguese"))

# Tokens sem pontuação e sem stopwords
tokens_sem_stopwords = [
    token.text
    for token in doc
    if token.text.lower() not in stop_pt and not token.is_punct
]

# Stemming com RSLP
stemmer = RSLPStemmer()

stems = [
    stemmer.stem(token.text.lower())
    for token in doc
    if not token.is_punct
]

# Lematização com spaCy
lemas = [
    token.lemma_.lower()
    for token in doc
    if not token.is_punct
]

print("Frase original:")
print(frase)

print("\nTokens sem stopwords:")
print(tokens_sem_stopwords)

print("\nStemming:")
print(stems)

print("\nLematização:")
print(lemas)

Frase original:
Bom dia! Meu nome é Marcos Ferreira e tenho interesse no apartamento anunciado na Rua Voluntários da Pátria, em Matão.

Tokens sem stopwords:
['Bom', 'dia', 'nome', 'Marcos', 'Ferreira', 'interesse', 'apartamento', 'anunciado', 'Rua', 'Voluntários', 'Pátria', 'Matão']

Stemming:
['bom', 'dia', 'meu', 'nom', 'é', 'marc', 'ferr', 'e', 'tenh', 'inter', 'no', 'apart', 'anunci', 'na', 'rua', 'voluntári', 'da', 'pátr', 'em', 'mat']

Lematização:
['bom', 'dia', 'meu', 'nome', 'ser', 'marcos', 'ferreira', 'e', 'ter', 'interesse', 'em o', 'apartamento', 'anunciar', 'em o', 'rua', 'voluntários', 'de o', 'pátria', 'em', 'matão']

In [20]:
# Tabela comparativa

tokens_originais = [
    token.text
    for token in doc
    if not token.is_punct
]

tabela_etapa2 = pd.DataFrame({
    "Original": tokens_originais,

    "Sem Stopword": [
        token.text if token.text.lower() not in stop_pt else "-"
        for token in doc
        if not token.is_punct
    ],

    "Stemming": stems,

    "Lematização": lemas
})

tabela_etapa2

       Original Sem Stopword   Stemming  Lematização
0           Bom          Bom        bom          bom
1           dia          dia        dia          dia
2           Meu            -        meu          meu
3          nome         nome        nom         nome
4             é            -          é          ser
5        Marcos       Marcos       marc       marcos
6      Ferreira     Ferreira       ferr     ferreira
7             e            -          e            e
8         tenho            -       tenh          ter
9     interesse    interesse      inter    interesse
10           no            -         no         em o
11  apartamento  apartamento      apart  apartamento
12    anunciado    anunciado     anunci     anunciar
13           na            -         na         em o
14          Rua          Rua        rua          rua
15  Voluntários  Voluntários  voluntári  voluntários
16           da            -         da         de o
17       Pátria       Pátria       pátr       pátria
18           em            -         em           em
19        Matão        Matão        mat        matão

## 3. Análise Sintática

In [21]:
# ETAPA 3 - ANÁLISE SINTÁTICA

frases_sintaticas = [
    corpus[1],
    corpus[3]
]

docs_sintaticos = [nlp(frase) for frase in frases_sintaticas]

for i, doc in enumerate(docs_sintaticos):
    print(f"\nFrase {i+1}:")
    print(doc.text)

    print("\nTokens, classe gramatical e dependência:")
    for token in doc:
        print(
            f"{token.text:20} "
            f"POS={token.pos_:10} "
            f"DEP={token.dep_:10} "
            f"HEAD={token.head.text}"
        )

Frase 1:
Vocês trabalham com financiamento pela Caixa Econômica Federal para imóveis usados?

Tokens, classe gramatical e dependência:
Vocês                POS=PRON       DEP=nsubj      HEAD=trabalham
trabalham            POS=VERB       DEP=ROOT       HEAD=trabalham
com                  POS=ADP        DEP=case       HEAD=financiamento
financiamento        POS=NOUN       DEP=obl        HEAD=trabalham
pela                 POS=ADP        DEP=case       HEAD=Caixa
Caixa                POS=PROPN      DEP=nmod       HEAD=financiamento
Econômica            POS=PROPN      DEP=flat:name  HEAD=Caixa
Federal              POS=PROPN      DEP=flat:name  HEAD=Caixa
para                 POS=ADP        DEP=case       HEAD=imóveis
imóveis              POS=NOUN       DEP=obl        HEAD=trabalham
usados               POS=VERB       DEP=acl        HEAD=imóveis
?                    POS=PUNCT      DEP=punct      HEAD=trabalham

Frase 2:
Qual é o valor do condomínio e do IPTU do apartamento no centro de Araraquara?

Tokens, classe gramatical e dependência:
Qual                 POS=PRON       DEP=ROOT       HEAD=Qual
é                    POS=AUX        DEP=cop        HEAD=Qual
o                    POS=DET        DEP=det        HEAD=valor
valor                POS=NOUN       DEP=nsubj      HEAD=Qual
do                   POS=ADP        DEP=case       HEAD=condomínio
condomínio           POS=NOUN       DEP=nmod       HEAD=valor
e                    POS=CCONJ      DEP=cc         HEAD=IPTU
do                   POS=ADP        DEP=case       HEAD=IPTU
IPTU                 POS=PROPN      DEP=conj       HEAD=condomínio
do                   POS=ADP        DEP=case       HEAD=apartamento
apartamento          POS=NOUN       DEP=nmod       HEAD=IPTU
no                   POS=ADP        DEP=case       HEAD=centro
centro               POS=NOUN       DEP=nmod       HEAD=apartamento
de                   POS=ADP        DEP=case       HEAD=Araraquara
Araraquara           POS=PROPN      DEP=nmod       HEAD=centro
?                    POS=PUNCT      DEP=punct      HEAD=Qual

In [22]:
# Identificação de ROOT, Sintagma Nominal (SN) e Sintagma Verbal (SV)

for i, doc in enumerate(docs_sintaticos):

    print(f"\n{'='*60}")
    print(f"Frase {i+1}: {doc.text}")

    # ROOT
    roots = [token for token in doc if token.dep_ == "ROOT"]

    print("\nROOT:")
    for root in roots:
        print(root.text)

    # Sujeito / Sintagma Nominal
    sujeitos = [token for token in doc if token.dep_ in ("nsubj", "nsubj:pass")]

    print("\nSintagma Nominal (SN):")
    for sujeito in sujeitos:
        sn = list(sujeito.subtree)
        print(" ".join(token.text for token in sn))

    # Sintagma Verbal
    print("\nSintagma Verbal (SV):")
    for root in roots:
        sv = list(root.subtree)

        # Remove os tokens que pertencem ao sujeito
        tokens_sujeito = []
        for sujeito in sujeitos:
            tokens_sujeito.extend(list(sujeito.subtree))

        sv = [token for token in sv if token not in tokens_sujeito]

        print(" ".join(token.text for token in sv))

============================================================
Frase 1: Vocês trabalham com financiamento pela Caixa Econômica Federal para imóveis usados?

ROOT:
trabalham

Sintagma Nominal (SN):
Vocês

Sintagma Verbal (SV):
trabalham com financiamento pela Caixa Econômica Federal para imóveis usados ?

============================================================
Frase 2: Qual é o valor do condomínio e do IPTU do apartamento no centro de Araraquara?

ROOT:
Qual

Sintagma Nominal (SN):
o valor do condomínio e do IPTU do apartamento no centro de Araraquara

Sintagma Verbal (SV):
Qual é ?

## 4. Interpretação Semântica

In [23]:
# ETAPA 4 - INTERPRETAÇÃO SEMÂNTICA

pares = [
    ("apartamento", "imóvel"),
    ("financiamento", "aluguel")
]

for palavra1, palavra2 in pares:
    doc1 = nlp_md(palavra1)
    doc2 = nlp_md(palavra2)

    similaridade = doc1.similarity(doc2)

    print(f"{palavra1} x {palavra2}")
    print(f"Similaridade: {similaridade:.4f}")
    print()

apartamento x imóvel
Similaridade: 0.6667

financiamento x aluguel
Similaridade: 0.3090

In [24]:
# Tabela de similaridade semântica

resultados_semanticos = []

for palavra1, palavra2 in pares:
    doc1 = nlp_md(palavra1)
    doc2 = nlp_md(palavra2)

    similaridade = doc1.similarity(doc2)

    resultados_semanticos.append({
        "Palavra 1": palavra1,
        "Palavra 2": palavra2,
        "Similaridade": round(similaridade, 4)
    })

tabela_semantica = pd.DataFrame(resultados_semanticos)

tabela_semantica

       Palavra 1 Palavra 2  Similaridade
0    apartamento    imóvel        0.6667
1  financiamento   aluguel        0.3090

## 5. Extração de Features

In [25]:
# ETAPA 5 - EXTRAÇÃO DE FEATURES

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [26]:
# Lematizando todos os documentos

corpus_lematizado = []

for doc in docs:

    lemas_doc = [
        token.lemma_.lower()
        for token in doc
        if not token.is_punct
        and not token.is_space
    ]

    corpus_lematizado.append(" ".join(lemas_doc))

print("Corpus lematizado:\n")

for i, texto in enumerate(corpus_lematizado):
    print(f"Documento {i+1}:")
    print(texto)
    print()

Corpus lematizado:

Documento 1:
bom dia meu nome ser marcos ferreira e ter interesse em o apartamento anunciar em o rua voluntários de o pátria em matão

Documento 2:
você trabalhar com financiamento por o caixa econômica federal para imóvel usar

Documento 3:
gostaria de agendar um visita a o imóvel de o bairro jardim europa em este semana

Documento 4:
qual ser o valor de o condomínio e de o iptu de o apartamento em o centro de araraquara

Documento 5:
o casa em o vila mariana ainda estar disponível para locação

Documento 6:
aceitam fiador ou seguro fiançar para o contrato de aluguel

Documento 7:
ser o corretora camila souza entrar em contato sobre o interesse de o cliente joão pedro em o imóvel de ribeirão preto

Documento 8:
o apartamento ser novo ou já ser reformar recentemente

Documento 9:
qual o prazo médio de aprovação de o financiamento bancário

Documento 10:
estar buscar um imóvel próximo a o shopping iguatemi para compra a o vista

Documento 11:
o sobrado em o bairro santa cecília aceitar animal de estimação

Documento 12:
poderiam enviar mais foto de o apartamento e de o planto baixo

Documento 13:
qual ser o taxa de juro aplicar por o banco de o brasil em esse tipo de financiamento

Documento 14:
o casa alugar ter vaga de garagem cobrir

Documento 15:
ter interesse em investir em um imóvel para locação de longo prazo

Documento 16:
poderia eu indicar imóvel disponível em o região central de matão

In [27]:
# Bag-of-Words

bow_vectorizer = CountVectorizer()

bow_matrix = bow_vectorizer.fit_transform(corpus_lematizado)

bow_df = pd.DataFrame(
    bow_matrix.toarray(),
    columns=bow_vectorizer.get_feature_names_out(),
    index=[f"Documento {i+1}" for i in range(len(corpus))]
)

bow_df

,aceitam,aceitar,agendar,ainda,alugar,aluguel,animal,anunciar,apartamento,aplicar,...,trabalhar,um,usar,vaga,valor,vila,visita,vista,você,voluntários
Documento 1,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,1
Documento 2,0,0,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,1,0
Documento 3,0,0,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
Documento 4,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
Documento 5,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
Documento 6,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Documento 7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Documento 8,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
Documento 9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Documento 10,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
Documento 11,0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Documento 12,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
Documento 13,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
Documento 14,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
Documento 15,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
Documento 16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [28]:
# Matriz TF-IDF

tfidf_vectorizer = TfidfVectorizer()

tfidf_matrix = tfidf_vectorizer.fit_transform(corpus_lematizado)

tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=tfidf_vectorizer.get_feature_names_out(),
    index=[f"Documento {i+1}" for i in range(len(corpus))]
)

tfidf_df

,aceitam,aceitar,agendar,ainda,alugar,aluguel,animal,anunciar,apartamento,aplicar,...,trabalhar,um,usar,vaga,valor,vila,visita,vista,você,voluntários
Documento 1,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.256505,0.181656,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.256505
Documento 2,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.330597,0.000000,0.330597,0.00000,0.000000,0.000000,0.000000,0.000000,0.330597,0.000000
Documento 3,0.000000,0.000000,0.322462,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.251281,0.000000,0.00000,0.000000,0.000000,0.322462,0.000000,0.000000,0.000000
Documento 4,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.231244,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.326526,0.000000,0.000000,0.000000,0.000000,0.000000
Documento 5,0.000000,0.000000,0.000000,0.386508,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.386508,0.000000,0.000000,0.000000,0.000000
Documento 6,0.369001,0.000000,0.000000,0.000000,0.00000,0.369001,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Documento 7,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Documento 8,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.268621,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Documento 9,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Documento 10,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.272969,0.000000,0.00000,0.000000,0.000000,0.000000,0.350294,0.000000,0.000000
Documento 11,0.000000,0.373739,0.000000,0.000000,0.00000,0.000000,0.373739,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Documento 12,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.264774,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Documento 13,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.300131,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Documento 14,0.000000,0.000000,0.000000,0.000000,0.42529,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.42529,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Documento 15,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.289688,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Documento 16,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [29]:
# Quantidade de palavras únicas por documento

palavras_unicas = []

for i, texto in enumerate(corpus_lematizado):

    palavras = texto.split()
    unicas = set(palavras)

    palavras_unicas.append({
        "Documento": f"Documento {i+1}",
        "Palavras únicas": len(unicas)
    })

palavras_unicas_df = pd.DataFrame(palavras_unicas)

palavras_unicas_df

       Documento  Palavras únicas
0    Documento 1               19
1    Documento 2               12
2    Documento 3               14
3    Documento 4               12
4    Documento 5               10
5    Documento 6               10
6    Documento 7               17
7    Documento 8                8
8    Documento 9                8
9   Documento 10               12
10  Documento 11               10
11  Documento 12               10
12  Documento 13               14
13  Documento 14                8
14  Documento 15               11
15  Documento 16               11

In [30]:
# Documento com maior quantidade de palavras únicas

maior = palavras_unicas_df.loc[
    palavras_unicas_df["Palavras únicas"].idxmax()
]

print(
    f"O documento com mais palavras únicas é "
    f"{maior['Documento']}, com "
    f"{maior['Palavras únicas']} palavras únicas."
)

O documento com mais palavras únicas é Documento 1, com 19 palavras únicas.

In [31]:
# Encontrando o maior valor de TF-IDF

maior_valor = tfidf_df.to_numpy().max()

linha, coluna = np.unravel_index(
    tfidf_df.to_numpy().argmax(),
    tfidf_df.shape
)

documento_maior_tfidf = tfidf_df.index[linha]
palavra_maior_tfidf = tfidf_df.columns[coluna]

print("Documento:", documento_maior_tfidf)
print("Palavra:", palavra_maior_tfidf)
print("TF-IDF:", round(maior_valor, 4))

Documento: Documento 4
Palavra: de
TF-IDF: 0.5275

## 6. Descoberta de Conhecimento em Textos (KDT)

In [32]:
# ETAPA 6 - DESCOBERTA DE CONHECIMENTO EM TEXTOS (KDT)

documentos_ner = [
    corpus[0],
    corpus[1],
    corpus[6],
    corpus[12]
]

for i, texto in enumerate(documentos_ner):

    doc = nlp(texto)

    print("\n" + "=" * 70)
    print(f"Documento selecionado {i+1}")
    print(texto)

    print("\nEntidades encontradas:")

    if doc.ents:

        for ent in doc.ents:
            print(
                f"{ent.text} --> {ent.label_}"
            )

    else:
        print("Nenhuma entidade encontrada.")

======================================================================
Documento selecionado 1
Bom dia! Meu nome é Marcos Ferreira e tenho interesse no apartamento anunciado na Rua Voluntários da Pátria, em Matão.

Entidades encontradas:
Marcos Ferreira --> PER
Rua Voluntários da Pátria --> LOC
Matão --> LOC

======================================================================
Documento selecionado 2
Vocês trabalham com financiamento pela Caixa Econômica Federal para imóveis usados?

Entidades encontradas:
Vocês --> LOC
Caixa Econômica Federal --> ORG

======================================================================
Documento selecionado 3
Sou a corretora Camila Souza, entrando em contato sobre o interesse do cliente João Pedro no imóvel de Ribeirão Preto.

Entidades encontradas:
Camila Souza --> PER
João Pedro --> PER
Ribeirão Preto --> LOC

======================================================================
Documento selecionado 4
Qual é a taxa de juros aplicada pelo Banco do Brasil nesse tipo de financiamento?

Entidades encontradas:
Banco do Brasil --> ORG

In [33]:
# Palavras-chave de cada documento

for i in range(len(tfidf_df)):

    documento = tfidf_df.iloc[i]

    principais = documento.sort_values(
        ascending=False
    ).head(5)

    print("\n" + "=" * 60)
    print(f"Documento {i+1}")

    for palavra, valor in principais.items():
        print(
            f"{palavra}: {valor:.4f}"
        )

============================================================
Documento 1
em: 0.3751
anunciar: 0.2565
bom: 0.2565
dia: 0.2565
ferreira: 0.2565

============================================================
Documento 2
econômica: 0.3306
federal: 0.3306
com: 0.3306
caixa: 0.3306
trabalhar: 0.3306

============================================================
Documento 3
agendar: 0.3225
este: 0.3225
europa: 0.3225
gostaria: 0.3225
semana: 0.3225

============================================================
Documento 4
de: 0.5275
araraquara: 0.3265
condomínio: 0.3265
centro: 0.3265
valor: 0.3265

============================================================
Documento 5
ainda: 0.3865
mariana: 0.3865
vila: 0.3865
estar: 0.3366
disponível: 0.3366

============================================================
Documento 6
aceitam: 0.3690
aluguel: 0.3690
contrato: 0.3690
fiador: 0.3690
fiançar: 0.3690

============================================================
Documento 7
corretora: 0.2673
contato: 0.2673
cliente: 0.2673
entrar: 0.2673
camila: 0.2673

============================================================
Documento 8
ser: 0.4932
novo: 0.3793
já: 0.3793
recentemente: 0.3793
reformar: 0.3793

============================================================
Documento 9
bancário: 0.4216
aprovação: 0.4216
médio: 0.4216
prazo: 0.3672
de: 0.3406

============================================================
Documento 10
compra: 0.3503
buscar: 0.3503
vista: 0.3503
iguatemi: 0.3503
próximo: 0.3503

============================================================
Documento 11
aceitar: 0.3737
animal: 0.3737
estimação: 0.3737
cecília: 0.3737
santa: 0.3737

============================================================
Documento 12
baixo: 0.3739
enviar: 0.3739
planto: 0.3739
foto: 0.3739
mais: 0.3739

============================================================
Documento 13
de: 0.3637
banco: 0.3001
brasil: 0.3001
aplicar: 0.3001
esse: 0.3001

============================================================
Documento 14
alugar: 0.4253
cobrir: 0.4253
vaga: 0.4253
garagem: 0.4253
casa: 0.3704

============================================================
Documento 15
longo: 0.3717
investir: 0.3717
em: 0.3624
locação: 0.3237
prazo: 0.3237

============================================================
Documento 16
eu: 0.3707
central: 0.3707
poderia: 0.3707
indicar: 0.3707
região: 0.3707

In [34]:
from sklearn.decomposition import LatentDirichletAllocation

In [35]:
# Treinamento do LDA

lda = LatentDirichletAllocation(
    n_components=2,
    random_state=42
)

lda_matrix = lda.fit_transform(bow_matrix)

print("LDA treinado com sucesso.")

LDA treinado com sucesso.

In [36]:
# Palavras principais de cada tópico

feature_names = bow_vectorizer.get_feature_names_out()

n_palavras = 8

for topico_idx, topico in enumerate(lda.components_):

    palavras = [
        feature_names[i]
        for i in topico.argsort()[
            :-n_palavras - 1:-1
        ]
    ]

    print(
        f"\nTópico {topico_idx + 1}:"
    )

    print(", ".join(palavras))

Tópico 1:
de, em, ser, apartamento, interesse, ter, imóvel, matão

Tópico 2:
de, em, para, imóvel, financiamento, um, qual, por

In [37]:
# Distribuição dos tópicos por documento

distribuicao_lda = pd.DataFrame(
    lda_matrix,
    columns=[
        "Tópico 1",
        "Tópico 2"
    ],
    index=[
        f"Documento {i+1}"
        for i in range(len(corpus))
    ]
)

distribuicao_lda

              Tópico 1  Tópico 2
Documento 1   0.972956  0.027044
Documento 2   0.044800  0.955200
Documento 3   0.043528  0.956472
Documento 4   0.953214  0.046786
Documento 5   0.068221  0.931779
Documento 6   0.942047  0.057953
Documento 7   0.970529  0.029471
Documento 8   0.941248  0.058752
Documento 9   0.066948  0.933052
Documento 10  0.049825  0.950175
Documento 11  0.058993  0.941007
Documento 12  0.066067  0.933933
Documento 13  0.046802  0.953198
Documento 14  0.928092  0.071908
Documento 15  0.938361  0.061639
Documento 16  0.946165  0.053835

In [38]:
# Tópico predominante em cada documento

distribuicao_lda["Tópico predominante"] = (
    distribuicao_lda[
        ["Tópico 1", "Tópico 2"]
    ].idxmax(axis=1)
)

distribuicao_lda

              Tópico 1  Tópico 2 Tópico predominante
Documento 1   0.972956  0.027044            Tópico 1
Documento 2   0.044800  0.955200            Tópico 2
Documento 3   0.043528  0.956472            Tópico 2
Documento 4   0.953214  0.046786            Tópico 1
Documento 5   0.068221  0.931779            Tópico 2
Documento 6   0.942047  0.057953            Tópico 1
Documento 7   0.970529  0.029471            Tópico 1
Documento 8   0.941248  0.058752            Tópico 1
Documento 9   0.066948  0.933052            Tópico 2
Documento 10  0.049825  0.950175            Tópico 2
Documento 11  0.058993  0.941007            Tópico 2
Documento 12  0.066067  0.933933            Tópico 2
Documento 13  0.046802  0.953198            Tópico 2
Documento 14  0.928092  0.071908            Tópico 1
Documento 15  0.938361  0.061639            Tópico 1
Documento 16  0.946165  0.053835            Tópico 1

## 7. Conclusão Integradora

As etapas do pipeline de PLN estão relacionadas e servem de base umas para as outras. A tokenização permitiu dividir os documentos em unidades que puderam ser analisadas individualmente. A normalização, por meio da remoção de stopwords, stemming e lematização, ajudou a reduzir variações das palavras e preparar o texto para a extração de características. A análise sintática acrescentou informações sobre a função das palavras e suas relações dentro das frases, enquanto a similaridade semântica permitiu comparar os significados de termos do corpus. Essas etapas foram importantes para as etapas finais, pois a lematização, por exemplo, foi utilizada antes da construção das matrizes Bag-of-Words e TF-IDF. Um exemplo concreto é a relação entre “apartamento” e “imóvel”: a análise semântica apresentou similaridade de 0,6667, enquanto o TF-IDF permitiu identificar quais palavras eram mais características de cada documento. Dessa forma, as técnicas estudadas ao longo do semestre formam um pipeline integrado para transformar textos em informações que podem ser analisadas e utilizadas na descoberta de conhecimento.